### ISSUE TITLE
static tests fail after new site spinup, because web/themes/custom and web/modules/custom directories do not exist

### ISSUE THREAD

**Issue by aaronbauman** [United-Philanthropy-Forum/km-starter-kit#35]
The composer `lint` job (triggered by `.ci/test/static/run`) fails because it's trying to run on directories that don't exist.

e.g. https://app.circleci.com/pipelines/github/United-Philanthropy-Forum/messageagency-km-test4/1/workflows/654f8b38-b3c8-432c-80cc-105353df7dd2/jobs/3
<img width="900" alt="Screenshot 2023-02-20 at 10 17 18 AM" src="https://user-images.githubusercontent.com/508451/220144412-56b09ef8-a35b-4775-981c-6f33ffd34599.png">

Adding the directories with `.gitkeep`s to this repo would fix it, but maybe there's a reason it hasn't been done?

**Comment by unclegcb** [comment]
Naw, it's because we haven't really spun up that many sites and we just create those directories early in the process. I suspect a .gitkeep would be a great time/confusion saver here.

**Comment by aaronbauman** [comment]
https://github.com/United-Philanthropy-Forum/km-starter-kit/pull/36 merged. Closing.
